DROP TABLE IF EXISTS micro_niches CASCADE;
DROP TABLE IF EXISTS sub_niches CASCADE;
DROP TABLE IF EXISTS niches CASCADE;
DROP TABLE IF EXISTS macro_niches CASCADE;

CREATE TABLE macro_niches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE niches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  macro_id UUID REFERENCES macro_niches(id) ON DELETE CASCADE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE sub_niches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  niche_id UUID REFERENCES niches(id) ON DELETE CASCADE,
  macro_id UUID REFERENCES macro_niches(id) ON DELETE CASCADE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE micro_niches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  sub_niche_id UUID REFERENCES sub_niches(id) ON DELETE CASCADE,
  niche_id UUID REFERENCES niches(id) ON DELETE CASCADE,
  macro_id UUID REFERENCES macro_niches(id) ON DELETE CASCADE,
  seed_keyword TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE macro_niches ENABLE ROW LEVEL SECURITY;
ALTER TABLE niches ENABLE ROW LEVEL SECURITY;
ALTER TABLE sub_niches ENABLE ROW LEVEL SECURITY;
ALTER TABLE micro_niches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read macro_niches taxonomy" ON macro_niches FOR SELECT USING (true);
CREATE POLICY "Public read niches taxonomy" ON niches FOR SELECT USING (true);
CREATE POLICY "Public read sub_niches taxonomy" ON sub_niches FOR SELECT USING (true);
CREATE POLICY "Public read micro_niches taxonomy" ON micro_niches FOR SELECT USING (true);

INSERT INTO macro_niches (slug, name, description, icon) VALUES
('bien-etre-recuperation', 'Bien-être & Récupération', 'Sauna, cryo, balnéo, pressothérapie, luminothérapie, massage', '🧖'),
('fitness-sport-maison', 'Fitness & Sport maison', 'Équipement home gym haut de gamme, cardio, musculation', '💪'),
('amenagement-exterieur', 'Aménagement extérieur', 'Pergolas, carports, abris, terrasses, piscines, spas', '🏡'),
('mobilier-decoration-premium', 'Mobilier & Décoration premium', 'Canapés design, luminaires, mobilier sur-mesure', '🛋️'),
('cuisine-art-de-vivre', 'Cuisine & Art de vivre', 'Électroménager premium, cave à vin, BBQ, cuisine extérieure', '🍷'),
('jardin-outdoor-lifestyle', 'Jardin & Outdoor lifestyle', 'Tondeuses robots, serres, irrigation, éclairage jardin', '🌿'),
('confort-habitat-intelligent', 'Confort & Habitat intelligent', 'Domotique, stores motorisés, chauffage, acoustique, bureau', '🏠'),
('mobilite-transport', 'Mobilité & Transport', 'Vélos électriques, trottinettes, équipement auto, van', '🚲'),
('animaux-premium', 'Animaux premium', 'Équipement haut de gamme chiens, chats, équidés', '🐾'),
('b2b-pro', 'B2B Pro & Équipement professionnel', 'Kiné, restauration, atelier, énergie, médical', '🏥');

INSERT INTO niches (slug, name, macro_id, description) VALUES
('sauna-balneotherapie', 'Sauna & Balnéothérapie', (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Saunas infrarouges, traditionnels, bains nordiques'),
('cryotherapie-bain-froid', 'Cryothérapie & Bain froid', (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Bains froids, cabines cryo, récupération par le froid'),
('pressotherapie-drainage', 'Pressothérapie & Drainage', (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Appareils pressothérapie jambes et corps entier'),
('luminotherapie-photobiomodulation', 'Luminothérapie & Photobiomodulation', (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Panneaux LED rouge, lampes bien-être, LLLT'),
('massage-relaxation', 'Massage & Relaxation', (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Fauteuils massage, tables, pistolets percussifs'),
('cardio-equipment', 'Cardio Equipment', (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Vélos, tapis de course, rameurs, elliptiques'),
('musculation-force', 'Musculation & Force', (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Stations musculation, haltères, bancs'),
('yoga-mobilite', 'Yoga & Mobilité', (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Équipement yoga premium, tables inversion'),
('sports-combat', 'Sports de combat & Arts martiaux', (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Sacs de frappe, équipement MMA, tatamis'),
('pergolas-abris', 'Pergolas & Abris', (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Pergolas bioclimatiques, alu, abris terrasse'),
('carports-abris-vehicules', 'Carports & Abris véhicules', (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Carports solaires, alu, abris moto vélo'),
('piscines-spa', 'Piscines & Spa', (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Piscines hors-sol, jacuzzis, abris piscine'),
('clotures-portails', 'Clôtures & Portails', (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Portails motorisés, clôtures premium'),
('mobilier-exterieur-premium', 'Mobilier extérieur premium', (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Salons jardin, tables, parasols'),
('mobilier-salon-design', 'Mobilier de salon design', (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Canapés, tables basses, meubles TV design'),
('mobilier-chambre-premium', 'Mobilier de chambre premium', (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Lits design, armoires, sommiers'),
('luminaires-eclairage-design', 'Luminaires & Éclairage design', (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Suspensions, appliques, éclairage architectural'),
('decoration-interieure-premium', 'Décoration intérieure premium', (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Murs végétaux, tableaux, tapis premium'),
('electromenager-premium', 'Électroménager premium', (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Robots culinaires, machines café, réfrigération'),
('cuisine-exterieure-bbq', 'Cuisine extérieure & BBQ', (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Barbecues premium, planchas, cuisines extérieures'),
('conservation-oenologie', 'Conservation & Œnologie', (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Caves à vin, accessoires œnologie'),
('chauffage-ambiance', 'Chauffage ambiance & Décoration feu', (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Cheminées bioéthanol, braseros, chauffage terrasse'),
('tondeuses-entretien-pelouse', 'Tondeuses & Entretien pelouse', (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Robots tondeuses, autoportées, débroussailleuses'),
('serres-potagers', 'Serres & Potagers', (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Serres verre et polycarbonate, potagers'),
('irrigation-arrosage', 'Irrigation & Arrosage', (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Arrosage automatique, récupération eau pluie'),
('eclairage-securite-jardin', 'Éclairage & Sécurité jardin', (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Éclairage solaire, caméras extérieures'),
('domotique-maison-connectee', 'Domotique & Maison connectée', (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Box domotique, volets motorisés, éclairage smart'),
('chauffage-climatisation-premium', 'Chauffage & Climatisation premium', (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Poêles granulés, climatiseurs, radiateurs design'),
('isolation-confort-acoustique', 'Isolation & Confort acoustique', (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Panneaux acoustiques, cabines, isolation phonique'),
('confort-bureau-teletravail', 'Confort bureau & Télétravail', (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Bureaux ergonomiques, sièges, accessoires'),
('velos-electriques', 'Vélos électriques', (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'VAE urbains, cargo, VTT, gravel'),
('trottinettes-mobilite-douce', 'Trottinettes & Mobilité douce', (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'Trottinettes électriques, monoroues, gyropodes'),
('equipement-auto-premium', 'Équipement auto premium', (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'Bornes recharge VE, accessoires auto, van'),
('chiens-premium', 'Chiens premium', (SELECT id FROM macro_niches WHERE slug='animaux-premium'), 'Niches, sport canin, santé et bien-être'),
('chats-premium', 'Chats premium', (SELECT id FROM macro_niches WHERE slug='animaux-premium'), 'Arbres à chats design, litières auto'),
('equides-grands-animaux', 'Équidés & Grands animaux', (SELECT id FROM macro_niches WHERE slug='animaux-premium'), 'Équipement équitation premium'),
('equipement-medical-paramédical', 'Équipement médical & Paramédical', (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Kiné, instituts bien-être, matériel médical'),
('equipement-restauration-hotellerie', 'Équipement restauration & Hôtellerie', (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Cuisine pro, mobilier hôtellerie'),
('equipement-atelier-artisanat', 'Équipement atelier & Artisanat', (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Machines bois, métal, soudure'),
('energie-developpement-durable', 'Énergie & Développement durable', (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Solaire, batteries, PAC');

INSERT INTO sub_niches (slug, name, niche_id, macro_id, description) VALUES
('saunas-infrarouges-domestiques', 'Saunas infrarouges domestiques', (SELECT id FROM niches WHERE slug='sauna-balneotherapie'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Cabines infrarouge usage résidentiel'),
('saunas-traditionnels-vapeur', 'Saunas traditionnels à vapeur', (SELECT id FROM niches WHERE slug='sauna-balneotherapie'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Saunas finlandais et barrel bois'),
('bains-nordiques', 'Bains nordiques', (SELECT id FROM niches WHERE slug='sauna-balneotherapie'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Bains nordiques bois et inox'),
('bains-froids-domestiques', 'Bains froids domestiques', (SELECT id FROM niches WHERE slug='cryotherapie-bain-froid'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Cuves et plonges froides résidentielles'),
('cabines-cryotherapie', 'Cabines cryothérapie', (SELECT id FROM niches WHERE slug='cryotherapie-bain-froid'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Cabines cryo corps entier'),
('pressotherapie-jambes', 'Pressothérapie jambes', (SELECT id FROM niches WHERE slug='pressotherapie-drainage'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Bottes et combinaisons pressothérapie'),
('panneaux-led-rouge', 'Panneaux LED rouge thérapeutique', (SELECT id FROM niches WHERE slug='luminotherapie-photobiomodulation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Photobiomodulation corps entier et local'),
('lampes-luminotherapie', 'Lampes luminothérapie bien-être', (SELECT id FROM niches WHERE slug='luminotherapie-photobiomodulation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Lampes anti-déprime et simulateurs aube'),
('fauteuils-massage', 'Fauteuils de massage', (SELECT id FROM niches WHERE slug='massage-relaxation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Fauteuils massage premium zéro gravité'),
('tables-massage', 'Tables de massage', (SELECT id FROM niches WHERE slug='massage-relaxation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Tables massage électriques pro'),
('pistolets-massage', 'Pistolets de massage percussifs', (SELECT id FROM niches WHERE slug='massage-relaxation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'Appareils percussifs récupération musculaire'),
('velos-appartement', 'Vélos d''appartement', (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Vélos spinning et couchés premium'),
('tapis-course', 'Tapis de course', (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Tapis motorisés pro et sous bureau'),
('rameurs', 'Rameurs', (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Rameurs eau, air et magnétiques'),
('elliptiques-crosstrainers', 'Elliptiques & Cross-trainers', (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Elliptiques magnétiques connectés'),
('stations-musculation', 'Stations de musculation', (SELECT id FROM niches WHERE slug='musculation-force'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Stations multifonctions câbles et racks'),
('halteres-kettlebells', 'Haltères & Kettlebells', (SELECT id FROM niches WHERE slug='musculation-force'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Haltères ajustables et kettlebells premium'),
('bancs-musculation', 'Bancs de musculation', (SELECT id FROM niches WHERE slug='musculation-force'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Bancs réglables et pro'),
('yoga-premium', 'Équipement yoga premium', (SELECT id FROM niches WHERE slug='yoga-mobilite'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Tapis et accessoires yoga naturels'),
('tables-inversion', 'Tables d''inversion', (SELECT id FROM niches WHERE slug='yoga-mobilite'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Tables inversion motorisées'),
('sacs-frappe', 'Sacs de frappe & Punching-balls', (SELECT id FROM niches WHERE slug='sports-combat'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Sacs suspendus et sur pied pro'),
('equipement-mma', 'Équipement MMA & Boxe', (SELECT id FROM niches WHERE slug='sports-combat'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'Protection, tatamis, équipement combat'),
('pergolas-bioclimatiques', 'Pergolas bioclimatiques', (SELECT id FROM niches WHERE slug='pergolas-abris'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Pergolas lames orientables aluminium'),
('pergolas-alu-classiques', 'Pergolas aluminium classiques', (SELECT id FROM niches WHERE slug='pergolas-abris'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Pergolas alu toiture plate et polycarbonate'),
('abris-terrasse', 'Abris de terrasse', (SELECT id FROM niches WHERE slug='pergolas-abris'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Vérandas démontables et abris rétractables'),
('carports-solaires', 'Carports solaires', (SELECT id FROM niches WHERE slug='carports-abris-vehicules'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Carports photovoltaïques résidentiels'),
('carports-aluminium', 'Carports aluminium', (SELECT id FROM niches WHERE slug='carports-abris-vehicules'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Carports alu 1 et 2 voitures'),
('abris-moto-velo', 'Abris moto & Vélo électrique', (SELECT id FROM niches WHERE slug='carports-abris-vehicules'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Abris moto et vélo électrique sécurisés'),
('piscines-hors-sol', 'Piscines hors-sol premium', (SELECT id FROM niches WHERE slug='piscines-spa'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Piscines acier et bois'),
('jacuzzis-spas-exterieurs', 'Jacuzzis & Spas extérieurs', (SELECT id FROM niches WHERE slug='piscines-spa'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Spas rigides et bois premium'),
('abris-piscine-spa', 'Abris piscine & Spa', (SELECT id FROM niches WHERE slug='piscines-spa'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Abris coulissants et télescopiques'),
('portails-motorises', 'Portails motorisés', (SELECT id FROM niches WHERE slug='clotures-portails'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Portails coulissants et battants'),
('clotures-premium', 'Clôtures premium', (SELECT id FROM niches WHERE slug='clotures-portails'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Clôtures alu et palissades composite'),
('salons-jardin-premium', 'Salons de jardin premium', (SELECT id FROM niches WHERE slug='mobilier-exterieur-premium'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Salons résine tressée et teck'),
('parasols-protection-solaire', 'Parasols & Protection solaire', (SELECT id FROM niches WHERE slug='mobilier-exterieur-premium'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'Parasols déportés motorisés'),
('canapes-design-premium', 'Canapés design premium', (SELECT id FROM niches WHERE slug='mobilier-salon-design'), (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Canapés modulables et tissu premium'),
('tables-basses-design', 'Tables basses design', (SELECT id FROM niches WHERE slug='mobilier-salon-design'), (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Tables marbre métal et relevables'),
('lits-design', 'Lits design & Têtes de lit', (SELECT id FROM niches WHERE slug='mobilier-chambre-premium'), (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Lits coffres capitonnés et escamotables'),
('armoires-dressings', 'Armoires & Dressings', (SELECT id FROM niches WHERE slug='mobilier-chambre-premium'), (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Armoires miroir et dressings modulables'),
('sommiers-matelas-premium', 'Sommiers & Matelas premium', (SELECT id FROM niches WHERE slug='mobilier-chambre-premium'), (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Sommiers électriques et matelas mémoire'),
('suspensions-lustres-design', 'Suspensions & Lustres design', (SELECT id FROM niches WHERE slug='luminaires-eclairage-design'), (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Lustres cristal, wabi-sabi, chandeliers'),
('appliques-murales-design', 'Appliques murales design', (SELECT id FROM niches WHERE slug='luminaires-eclairage-design'), (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Appliques laiton marbre et industriel'),
('murs-vegetaux', 'Murs végétaux & Plantes design', (SELECT id FROM niches WHERE slug='decoration-interieure-premium'), (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Murs végétaux stabilisés et jardinières'),
('tapis-premium', 'Tapis premium', (SELECT id FROM niches WHERE slug='decoration-interieure-premium'), (SELECT id FROM macro_niches WHERE slug='mobilier-decoration-premium'), 'Tapis berbères laine naturelle et vinyle'),
('robots-culinaires', 'Robots culinaires multifonctions', (SELECT id FROM niches WHERE slug='electromenager-premium'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Robots pâtisserie et cuiseur vapeur'),
('machines-cafe-premium', 'Machines à café premium', (SELECT id FROM niches WHERE slug='electromenager-premium'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Machines grain automatiques et pro barista'),
('refrigeration-premium', 'Réfrigération premium', (SELECT id FROM niches WHERE slug='electromenager-premium'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Caves à vin et réfrigérateurs américains'),
('barbecues-premium', 'Barbecues premium', (SELECT id FROM niches WHERE slug='cuisine-exterieure-bbq'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Kamado céramique, gaz inox, fumoirs'),
('planchas-grills', 'Planchas & Grills', (SELECT id FROM niches WHERE slug='cuisine-exterieure-bbq'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Planchas gaz et électriques pro'),
('cuisines-exterieures-completes', 'Cuisines extérieures complètes', (SELECT id FROM niches WHERE slug='cuisine-exterieure-bbq'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Îlots modulaires et fours à bois'),
('caves-a-vin', 'Caves à vin', (SELECT id FROM niches WHERE slug='conservation-oenologie'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Caves service, vieillissement et enterrées'),
('cheminees-bioethanol', 'Cheminées bioéthanol design', (SELECT id FROM niches WHERE slug='chauffage-ambiance'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Cheminées murales et sur pied design'),
('braseros-tables-brasero', 'Braseros & Tables brasero', (SELECT id FROM niches WHERE slug='chauffage-ambiance'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Braseros outdoor et tables avec foyer'),
('chauffage-terrasse', 'Chauffage terrasse', (SELECT id FROM niches WHERE slug='chauffage-ambiance'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'Parasols chauffants et radiant infrarouge'),
('robots-tondeuses', 'Robots tondeuses', (SELECT id FROM niches WHERE slug='tondeuses-entretien-pelouse'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Robots sans fil périphérique et GPS'),
('tondeuses-autoportees', 'Tondeuses autoportées', (SELECT id FROM niches WHERE slug='tondeuses-entretien-pelouse'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Tractées et zero-turn'),
('serres-jardin', 'Serres de jardin', (SELECT id FROM niches WHERE slug='serres-potagers'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Serres verre trempé et polycarbonate'),
('potagers-surelevas', 'Potagers surélevés & Bacs', (SELECT id FROM niches WHERE slug='serres-potagers'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Bacs bois composite et acier galvanisé'),
('arrosage-automatique', 'Systèmes arrosage automatique', (SELECT id FROM niches WHERE slug='irrigation-arrosage'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Programmateurs connectés et goutte-à-goutte'),
('recuperation-eau-pluie', 'Récupération eau de pluie', (SELECT id FROM niches WHERE slug='irrigation-arrosage'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Citernes et cuves design'),
('eclairage-solaire-jardin', 'Éclairage solaire jardin', (SELECT id FROM niches WHERE slug='eclairage-securite-jardin'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Bornes et spots solaires LED'),
('cameras-surveillance-exterieure', 'Caméras surveillance extérieure', (SELECT id FROM niches WHERE slug='eclairage-securite-jardin'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'Caméras solaires et systèmes alarme'),
('volets-stores-motorises', 'Volets & Stores motorisés', (SELECT id FROM niches WHERE slug='domotique-maison-connectee'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Volets roulants et stores motorisés connectés'),
('eclairage-intelligent', 'Éclairage intelligent', (SELECT id FROM niches WHERE slug='domotique-maison-connectee'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'LED connecté et interrupteurs tactiles'),
('poeles-granules', 'Poêles à granulés', (SELECT id FROM niches WHERE slug='chauffage-climatisation-premium'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Insert et canalisables'),
('climatiseurs-pac', 'Climatiseurs & Pompes à chaleur', (SELECT id FROM niches WHERE slug='chauffage-climatisation-premium'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Réversibles monosplit et PAC air-air'),
('radiateurs-design', 'Radiateurs design', (SELECT id FROM niches WHERE slug='chauffage-climatisation-premium'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Sèche-serviettes et inertie pierre'),
('panneaux-acoustiques', 'Panneaux acoustiques', (SELECT id FROM niches WHERE slug='isolation-confort-acoustique'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Panneaux bois design et mousse studio'),
('cabines-acoustiques', 'Cabines acoustiques', (SELECT id FROM niches WHERE slug='isolation-confort-acoustique'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Phone booth et studios préfab'),
('bureaux-ergonomiques', 'Bureaux ergonomiques', (SELECT id FROM niches WHERE slug='confort-bureau-teletravail'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Assis-debout motorisés et muraux'),
('sieges-ergonomiques', 'Sièges ergonomiques', (SELECT id FROM niches WHERE slug='confort-bureau-teletravail'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'Chaises premium et sièges selle'),
('vae-urbains', 'VAE urbains', (SELECT id FROM niches WHERE slug='velos-electriques'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'Vélos électriques urbains et pliables'),
('vae-cargo', 'VAE cargo', (SELECT id FROM niches WHERE slug='velos-electriques'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'Vélos cargo familiaux et professionnels'),
('vae-vtt-gravel', 'VAE VTT & Gravel', (SELECT id FROM niches WHERE slug='velos-electriques'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'E-VTT tout-suspendu et e-gravel'),
('trottinettes-electriques', 'Trottinettes électriques', (SELECT id FROM niches WHERE slug='trottinettes-mobilite-douce'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'Longue portée et tout-terrain'),
('bornes-recharge-ve', 'Bornes de recharge VE', (SELECT id FROM niches WHERE slug='equipement-auto-premium'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'Bornes domestiques et copropriété'),
('tentes-toit-suv', 'Tentes de toit pour 4x4 & SUV', (SELECT id FROM niches WHERE slug='equipement-auto-premium'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'Tentes hardshell et softshell'),
('amenagements-van', 'Aménagements van & Camping-car', (SELECT id FROM niches WHERE slug='equipement-auto-premium'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'Conversion van et équipement solaire'),
('niches-hebergement-chien', 'Niches & Hébergement extérieur chien', (SELECT id FROM niches WHERE slug='chiens-premium'), (SELECT id FROM macro_niches WHERE slug='animaux-premium'), 'Niches isolées design et chenils'),
('sport-canin', 'Équipement sport canin', (SELECT id FROM niches WHERE slug='chiens-premium'), (SELECT id FROM macro_niches WHERE slug='animaux-premium'), 'Tapis de course et agility'),
('arbres-chats-design', 'Arbres à chats design', (SELECT id FROM niches WHERE slug='chats-premium'), (SELECT id FROM macro_niches WHERE slug='animaux-premium'), 'Arbres minimalistes et meubles muraux'),
('litieres-automatiques', 'Litières automatiques connectées', (SELECT id FROM niches WHERE slug='chats-premium'), (SELECT id FROM macro_niches WHERE slug='animaux-premium'), 'Litières connectées autonettoyantes'),
('equipement-equitation', 'Équipement équitation premium', (SELECT id FROM niches WHERE slug='equides-grands-animaux'), (SELECT id FROM macro_niches WHERE slug='animaux-premium'), 'Selles, harnachement et couvertures'),
('cabinets-kine', 'Équipement cabinets kinésithérapie', (SELECT id FROM niches WHERE slug='equipement-medical-paramédical'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Tables électriques et électrostimulation'),
('instituts-bien-etre-pro', 'Équipement instituts bien-être', (SELECT id FROM niches WHERE slug='equipement-medical-paramédical'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Spa hammam et cabines UV pro'),
('cuisine-pro', 'Équipement cuisine professionnelle', (SELECT id FROM niches WHERE slug='equipement-restauration-hotellerie'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Fours pro et réfrigération pro'),
('machines-bois-pro', 'Machines bois professionnelles', (SELECT id FROM niches WHERE slug='equipement-atelier-artisanat'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Scies sur table et tours industriels'),
('soudure-metal-pro', 'Équipement métal & Soudure', (SELECT id FROM niches WHERE slug='equipement-atelier-artisanat'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Postes MIG TIG et compresseurs'),
('kits-solaires', 'Kits solaires & Autoconsommation', (SELECT id FROM niches WHERE slug='energie-developpement-durable'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'Kits solaires et batteries stockage'),
('pompes-chaleur-pro', 'Pompes à chaleur', (SELECT id FROM niches WHERE slug='energie-developpement-durable'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'PAC air-eau et géothermique');

INSERT INTO micro_niches (slug, name, sub_niche_id, niche_id, macro_id, seed_keyword) VALUES
('saunas-infrarouges-1-2-places', 'Saunas infrarouges 1-2 places', (SELECT id FROM sub_niches WHERE slug='saunas-infrarouges-domestiques'), (SELECT id FROM niches WHERE slug='sauna-balneotherapie'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'sauna infrarouge 1 place'),
('saunas-infrarouges-3-4-places', 'Saunas infrarouges 3-4 places', (SELECT id FROM sub_niches WHERE slug='saunas-infrarouges-domestiques'), (SELECT id FROM niches WHERE slug='sauna-balneotherapie'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'sauna infrarouge 3 places'),
('saunas-barrel-bois-exterieur', 'Saunas barrel extérieurs', (SELECT id FROM sub_niches WHERE slug='saunas-traditionnels-vapeur'), (SELECT id FROM niches WHERE slug='sauna-balneotherapie'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'sauna barrel bois extérieur'),
('saunas-finlandais-maison', 'Saunas finlandais maison', (SELECT id FROM sub_niches WHERE slug='saunas-traditionnels-vapeur'), (SELECT id FROM niches WHERE slug='sauna-balneotherapie'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'sauna finlandais maison'),
('bains-nordiques-bois-poele', 'Bains nordiques bois chauffage bois', (SELECT id FROM sub_niches WHERE slug='bains-nordiques'), (SELECT id FROM niches WHERE slug='sauna-balneotherapie'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'bain nordique bois poele'),
('bains-nordiques-electriques', 'Bains nordiques électriques', (SELECT id FROM sub_niches WHERE slug='bains-nordiques'), (SELECT id FROM niches WHERE slug='sauna-balneotherapie'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'bain nordique électrique'),
('cuves-bain-froid-portables', 'Cuves de bain froid portables', (SELECT id FROM sub_niches WHERE slug='bains-froids-domestiques'), (SELECT id FROM niches WHERE slug='cryotherapie-bain-froid'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'cuve bain froid portable'),
('bains-froids-avec-refroidisseur', 'Bains froids avec refroidisseur intégré', (SELECT id FROM sub_niches WHERE slug='bains-froids-domestiques'), (SELECT id FROM niches WHERE slug='cryotherapie-bain-froid'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'bain froid chiller refroidisseur'),
('bottes-pressotherapie-domestiques', 'Bottes pressothérapie domestiques', (SELECT id FROM sub_niches WHERE slug='pressotherapie-jambes'), (SELECT id FROM niches WHERE slug='pressotherapie-drainage'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'bottes pressothérapie maison'),
('combinaisons-pressotherapie', 'Combinaisons pressothérapie corps entier', (SELECT id FROM sub_niches WHERE slug='pressotherapie-jambes'), (SELECT id FROM niches WHERE slug='pressotherapie-drainage'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'combinaison pressothérapie corps entier'),
('panneaux-led-rouge-corps-entier', 'Panneaux LED rouge corps entier', (SELECT id FROM sub_niches WHERE slug='panneaux-led-rouge'), (SELECT id FROM niches WHERE slug='luminotherapie-photobiomodulation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'panneau led rouge corps entier'),
('panneaux-led-rouge-visage', 'Panneaux LED rouge visage et local', (SELECT id FROM sub_niches WHERE slug='panneaux-led-rouge'), (SELECT id FROM niches WHERE slug='luminotherapie-photobiomodulation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'panneau led rouge visage'),
('fauteuils-massage-zero-gravite', 'Fauteuils massage zéro gravité', (SELECT id FROM sub_niches WHERE slug='fauteuils-massage'), (SELECT id FROM niches WHERE slug='massage-relaxation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'fauteuil massage zéro gravité'),
('fauteuils-massage-4d', 'Fauteuils massage 4D professionnels', (SELECT id FROM sub_niches WHERE slug='fauteuils-massage'), (SELECT id FROM niches WHERE slug='massage-relaxation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'fauteuil massage 4D shiatsu'),
('tables-massage-electriques-pro', 'Tables massage électriques pro', (SELECT id FROM sub_niches WHERE slug='tables-massage'), (SELECT id FROM niches WHERE slug='massage-relaxation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'table massage électrique professionnelle'),
('tables-massage-portables', 'Tables massage portables premium', (SELECT id FROM sub_niches WHERE slug='tables-massage'), (SELECT id FROM niches WHERE slug='massage-relaxation'), (SELECT id FROM macro_niches WHERE slug='bien-etre-recuperation'), 'table massage portable'),
('velos-spinning-magnetiques', 'Vélos spinning magnétiques', (SELECT id FROM sub_niches WHERE slug='velos-appartement'), (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'vélo spinning magnétique'),
('velos-connectes-premium', 'Vélos connectés premium', (SELECT id FROM sub_niches WHERE slug='velos-appartement'), (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'vélo appartement connecté'),
('tapis-course-motorises-pro', 'Tapis de course motorisés pro', (SELECT id FROM sub_niches WHERE slug='tapis-course'), (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'tapis course motorisé professionnel'),
('tapis-marche-sous-bureau', 'Tapis de marche sous bureau', (SELECT id FROM sub_niches WHERE slug='tapis-course'), (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'tapis marche sous bureau'),
('rameurs-eau-professionnels', 'Rameurs à eau professionnels', (SELECT id FROM sub_niches WHERE slug='rameurs'), (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'rameur eau professionnel'),
('rameurs-magnetiques-silencieux', 'Rameurs magnétiques silencieux', (SELECT id FROM sub_niches WHERE slug='rameurs'), (SELECT id FROM niches WHERE slug='cardio-equipment'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'rameur magnétique silencieux'),
('stations-multifonctions-cables', 'Stations multifonctions câbles', (SELECT id FROM sub_niches WHERE slug='stations-musculation'), (SELECT id FROM niches WHERE slug='musculation-force'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'station musculation multifonction câbles'),
('racks-squat-barres', 'Racks squat & Barres', (SELECT id FROM sub_niches WHERE slug='stations-musculation'), (SELECT id FROM niches WHERE slug='musculation-force'), (SELECT id FROM macro_niches WHERE slug='fitness-sport-maison'), 'rack squat barre musculation'),
('pergolas-bioclimatiques-adossees', 'Pergolas bioclimatiques adossées', (SELECT id FROM sub_niches WHERE slug='pergolas-bioclimatiques'), (SELECT id FROM niches WHERE slug='pergolas-abris'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'pergola bioclimatique adossée'),
('pergolas-bioclimatiques-autoportees', 'Pergolas bioclimatiques autoportées', (SELECT id FROM sub_niches WHERE slug='pergolas-bioclimatiques'), (SELECT id FROM niches WHERE slug='pergolas-abris'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'pergola bioclimatique autoportée'),
('verandas-demontables-4-saisons', 'Vérandas démontables 4 saisons', (SELECT id FROM sub_niches WHERE slug='abris-terrasse'), (SELECT id FROM niches WHERE slug='pergolas-abris'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'véranda démontable 4 saisons'),
('abris-terrasse-retractables', 'Abris terrasse rétractables', (SELECT id FROM sub_niches WHERE slug='abris-terrasse'), (SELECT id FROM niches WHERE slug='pergolas-abris'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'abri terrasse rétractable'),
('carports-photovoltaiques-1-voiture', 'Carports photovoltaïques 1 voiture', (SELECT id FROM sub_niches WHERE slug='carports-solaires'), (SELECT id FROM niches WHERE slug='carports-abris-vehicules'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'carport solaire 1 voiture'),
('carports-photovoltaiques-2-voitures', 'Carports photovoltaïques 2 voitures', (SELECT id FROM sub_niches WHERE slug='carports-solaires'), (SELECT id FROM niches WHERE slug='carports-abris-vehicules'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'carport solaire 2 voitures'),
('spas-rigides-exterieurs', 'Spas rigides extérieurs', (SELECT id FROM sub_niches WHERE slug='jacuzzis-spas-exterieurs'), (SELECT id FROM niches WHERE slug='piscines-spa'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'spa rigide extérieur'),
('spas-bois-premium', 'Spas extérieurs bois premium', (SELECT id FROM sub_niches WHERE slug='jacuzzis-spas-exterieurs'), (SELECT id FROM niches WHERE slug='piscines-spa'), (SELECT id FROM macro_niches WHERE slug='amenagement-exterieur'), 'spa bois premium'),
('bureaux-assis-debout-motorises', 'Bureaux assis-debout motorisés', (SELECT id FROM sub_niches WHERE slug='bureaux-ergonomiques'), (SELECT id FROM niches WHERE slug='confort-bureau-teletravail'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'bureau assis debout motorisé'),
('bureaux-muraux-rabattables', 'Bureaux muraux rabattables', (SELECT id FROM sub_niches WHERE slug='bureaux-ergonomiques'), (SELECT id FROM niches WHERE slug='confort-bureau-teletravail'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'bureau mural rabattable'),
('chaises-ergonomiques-premium', 'Chaises ergonomiques premium', (SELECT id FROM sub_niches WHERE slug='sieges-ergonomiques'), (SELECT id FROM niches WHERE slug='confort-bureau-teletravail'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'chaise ergonomique premium'),
('sieges-selle-genou', 'Sièges de selle & Genoux', (SELECT id FROM sub_niches WHERE slug='sieges-ergonomiques'), (SELECT id FROM niches WHERE slug='confort-bureau-teletravail'), (SELECT id FROM macro_niches WHERE slug='confort-habitat-intelligent'), 'siège selle ergonomique'),
('vae-urbains-pliables', 'VAE urbains pliables premium', (SELECT id FROM sub_niches WHERE slug='vae-urbains'), (SELECT id FROM niches WHERE slug='velos-electriques'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'vélo électrique pliable'),
('vae-step-through-design', 'VAE step-through design', (SELECT id FROM sub_niches WHERE slug='vae-urbains'), (SELECT id FROM niches WHERE slug='velos-electriques'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'vélo électrique step through'),
('vae-cargo-familiaux', 'Vélos cargo électriques familiaux', (SELECT id FROM sub_niches WHERE slug='vae-cargo'), (SELECT id FROM niches WHERE slug='velos-electriques'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'vélo cargo électrique famille'),
('vae-cargo-pro-livraison', 'Vélos cargo pro livraison', (SELECT id FROM sub_niches WHERE slug='vae-cargo'), (SELECT id FROM niches WHERE slug='velos-electriques'), (SELECT id FROM macro_niches WHERE slug='mobilite-transport'), 'vélo cargo électrique livraison'),
('caves-vin-service', 'Caves à vin de service', (SELECT id FROM sub_niches WHERE slug='caves-a-vin'), (SELECT id FROM niches WHERE slug='conservation-oenologie'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'cave à vin de service'),
('caves-vin-vieillissement', 'Caves à vin de vieillissement', (SELECT id FROM sub_niches WHERE slug='caves-a-vin'), (SELECT id FROM niches WHERE slug='conservation-oenologie'), (SELECT id FROM macro_niches WHERE slug='cuisine-art-de-vivre'), 'cave à vin de vieillissement'),
('robots-tondeuses-sans-fil', 'Robots tondeuses sans fil périphérique', (SELECT id FROM sub_niches WHERE slug='robots-tondeuses'), (SELECT id FROM niches WHERE slug='tondeuses-entretien-pelouse'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'robot tondeuse sans fil'),
('robots-tondeuses-gps', 'Robots tondeuses GPS', (SELECT id FROM sub_niches WHERE slug='robots-tondeuses'), (SELECT id FROM niches WHERE slug='tondeuses-entretien-pelouse'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'robot tondeuse GPS'),
('serres-verre-trempe', 'Serres verre trempé premium', (SELECT id FROM sub_niches WHERE slug='serres-jardin'), (SELECT id FROM niches WHERE slug='serres-potagers'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'serre jardin verre trempé'),
('serres-polycarbonate-grande-surface', 'Serres polycarbonate grande surface', (SELECT id FROM sub_niches WHERE slug='serres-jardin'), (SELECT id FROM niches WHERE slug='serres-potagers'), (SELECT id FROM macro_niches WHERE slug='jardin-outdoor-lifestyle'), 'serre polycarbonate grande surface'),
('kits-solaires-autoconsommation', 'Kits solaires autoconsommation', (SELECT id FROM sub_niches WHERE slug='kits-solaires'), (SELECT id FROM niches WHERE slug='energie-developpement-durable'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'kit solaire autoconsommation'),
('batteries-stockage-solaire', 'Batteries de stockage solaire', (SELECT id FROM sub_niches WHERE slug='kits-solaires'), (SELECT id FROM niches WHERE slug='energie-developpement-durable'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'batterie stockage énergie solaire'),
('pac-air-eau-residentiel', 'PAC air-eau résidentiel', (SELECT id FROM sub_niches WHERE slug='pompes-chaleur-pro'), (SELECT id FROM niches WHERE slug='energie-developpement-durable'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'pompe à chaleur air eau'),
('pac-geothermique', 'PAC géothermique', (SELECT id FROM sub_niches WHERE slug='pompes-chaleur-pro'), (SELECT id FROM niches WHERE slug='energie-developpement-durable'), (SELECT id FROM macro_niches WHERE slug='b2b-pro'), 'pompe à chaleur géothermique');

CREATE INDEX IF NOT EXISTS idx_niches_macro_id ON niches(macro_id);
CREATE INDEX IF NOT EXISTS idx_sub_niches_niche_id ON sub_niches(niche_id);
CREATE INDEX IF NOT EXISTS idx_sub_niches_macro_id ON sub_niches(macro_id);
CREATE INDEX IF NOT EXISTS idx_micro_niches_sub_niche_id ON micro_niches(sub_niche_id);
CREATE INDEX IF NOT EXISTS idx_micro_niches_seed_keyword ON micro_niches(seed_keyword);